name: Debug Secrets Access

on:
  workflow_dispatch:
  push:
    branches: [ debug-secrets ]

env:
  REGISTRY: shrtso.azurecr.io
  IMAGE_NAME: coolify-go

jobs:
  debug-secrets:
    runs-on: ubuntu-latest
    environment: PRD

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Debug Environment
      run: |
        echo "## Debug Information" >> $GITHUB_STEP_SUMMARY
        echo "**Event Name:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "**Ref:** ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
        echo "**Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "**Environment:** PRD" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY

    - name: Check if secrets exist
      run: |
        if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then
          echo "❌ AZURE_CLIENT_ID is empty or missing"
          echo "**AZURE_CLIENT_ID:** ❌ Missing" >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ AZURE_CLIENT_ID is present (length: ${#AZURE_CLIENT_ID})"
          echo "**AZURE_CLIENT_ID:** ✅ Present (${#AZURE_CLIENT_ID} chars)" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -z "${{ secrets.AZURE_CLIENT_SECRET }}" ]; then
          echo "❌ AZURE_CLIENT_SECRET is empty or missing"
          echo "**AZURE_CLIENT_SECRET:** ❌ Missing" >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ AZURE_CLIENT_SECRET is present (length: ${#AZURE_CLIENT_SECRET})"
          echo "**AZURE_CLIENT_SECRET:** ✅ Present (${#AZURE_CLIENT_SECRET} chars)" >> $GITHUB_STEP_SUMMARY
        fi
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Test Azure login (dry run)
      run: |
        echo "Testing Azure Container Registry login..."
        if [ -n "${{ secrets.AZURE_CLIENT_ID }}" ] && [ -n "${{ secrets.AZURE_CLIENT_SECRET }}" ]; then
          echo "Both secrets are available, login should work"
          echo "Registry: ${{ env.REGISTRY }}"
          echo "Username: ${{ secrets.AZURE_CLIENT_ID }}"
          echo "Password: [HIDDEN]"
        else
          echo "❌ One or both secrets are missing!"
          echo "This explains why the login is failing."
        fi

    - name: Environment info
      run: |
        echo "## Environment Variables" >> $GITHUB_STEP_SUMMARY
        echo "- REGISTRY: ${{ env.REGISTRY }}" >> $GITHUB_STEP_SUMMARY
        echo "- IMAGE_NAME: ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "## Troubleshooting Steps" >> $GITHUB_STEP_SUMMARY
        echo "1. Go to: Repository Settings → Environments → PRD → Environment secrets" >> $GITHUB_STEP_SUMMARY
        echo "2. Verify both secrets exist:" >> $GITHUB_STEP_SUMMARY
        echo "   - AZURE_CLIENT_ID" >> $GITHUB_STEP_SUMMARY
        echo "   - AZURE_CLIENT_SECRET" >> $GITHUB_STEP_SUMMARY
        echo "3. Re-run this workflow to test again" >> $GITHUB_STEP_SUMMARY
